// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBfveU-CIdQUXSsDVj4cXfdgN0KalQrBI',
    appId: '1:853771213854:web:2ed344154af9956938220f',
    messagingSenderId: '853771213854',
    projectId: 'wallet-4be39',
    authDomain: 'wallet-4be39.firebaseapp.com',
    storageBucket: 'wallet-4be39.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh1EWpgGvCcyGlbD9Qjejkpb5sAA-elwg',
    appId: '1:853771213854:android:6ad70e64bb018fbc38220f',
    messagingSenderId: '853771213854',
    projectId: 'wallet-4be39',
    storageBucket: 'wallet-4be39.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNqGzpQ5Dk5BF7Ter5klNE3W9XLZuzWsQ',
    appId: '1:853771213854:ios:2bd086c48b69697838220f',
    messagingSenderId: '853771213854',
    projectId: 'wallet-4be39',
    storageBucket: 'wallet-4be39.firebasestorage.app',
    iosBundleId: 'com.example.wallet',
  );
}
